/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 snowman.gltf 
Author: amogusstrikesback2 (https://sketchfab.com/amogusstrikesback2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chicken-gun-scary-snowman-4af436fc9e874cb78739f6aa1b27ae77
Title: chicken gun scary snowman
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function ModelSnowman(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/snowman.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={116.426}>
          <group name="snowmanfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="3_Snowman" position={[42.905, 0, 50.53]}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_7" position={[42.905, 1.273, 50.572]} rotation={[-Math.PI / 2, 0, 0]} scale={1.66} />
                    <group name="Object_9" position={[42.905, 1.273, 50.537]} rotation={[-1.499, 0, 0]} scale={1.66} />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.snowman_dif} skeleton={nodes.Object_8.skeleton} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.snowman_dif} skeleton={nodes.Object_10.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/snowman.gltf')
