/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dominic Baker (https://sketchfab.com/Domuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/halloween-pumpkin-0555c3a0722f433ab5bbc7059df5f271
Title: Halloween Pumpkin
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function HalloweenPumpkin(props) {
  const { nodes, materials } = useGLTF('/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Material_0}
        position={[-18, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/scene.gltf');